services:
  postgres:
    image: postgres:16
    container_name: text_to_sql
    restart: unless-stopped

    environment:
      POSTGRES_DB: text_to_sql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pankaj

    ports:
      - "15432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d text_to_sql"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
